export const COUNTRIES = [
  // アジア
  { id: 'af', name: 'アフガニスタン', slug: 'afghanistan', isDeveloping: true, countryCode: 'af', continent: 'asia' },
  { id: 'am', name: 'アルメニア', slug: 'armenia', isDeveloping: true, countryCode: 'am', continent: 'asia' },
  { id: 'az', name: 'アゼルバイジャン', slug: 'azerbaijan', isDeveloping: true, countryCode: 'az', continent: 'asia' },
  { id: 'bh', name: 'バーレーン', slug: 'bahrain', isDeveloping: false, countryCode: 'bh', continent: 'asia' },
  { id: 'bd', name: 'バングラデシュ', slug: 'bangladesh', isDeveloping: true, countryCode: 'bd', continent: 'asia' },
  { id: 'bt', name: 'ブータン', slug: 'bhutan', isDeveloping: true, countryCode: 'bt', continent: 'asia' },
  { id: 'bn', name: 'ブルネイ', slug: 'brunei', isDeveloping: false, countryCode: 'bn', continent: 'asia' },
  { id: 'kh', name: 'カンボジア', slug: 'cambodia', isDeveloping: true, countryCode: 'kh', continent: 'asia' },
  { id: 'cn', name: '中国', slug: 'china', isDeveloping: true, countryCode: 'cn', continent: 'asia' },
  { id: 'cy', name: 'キプロス', slug: 'cyprus', isDeveloping: false, countryCode: 'cy', continent: 'asia' },
  { id: 'ge', name: 'ジョージア', slug: 'georgia', isDeveloping: true, countryCode: 'ge', continent: 'asia' },
  { id: 'in', name: 'インド', slug: 'india', isDeveloping: true, countryCode: 'in', continent: 'asia' },
  { id: 'id', name: 'インドネシア', slug: 'indonesia', isDeveloping: true, countryCode: 'id', continent: 'asia' },
  { id: 'ir', name: 'イラン', slug: 'iran', isDeveloping: true, countryCode: 'ir', continent: 'asia' },
  { id: 'iq', name: 'イラク', slug: 'iraq', isDeveloping: true, countryCode: 'iq', continent: 'asia' },
  { id: 'il', name: 'イスラエル', slug: 'israel', isDeveloping: false, countryCode: 'il', continent: 'asia' },
  { id: 'jp', name: '日本', slug: 'japan', isDeveloping: false, countryCode: 'jp', continent: 'asia' },
  { id: 'jo', name: 'ヨルダン', slug: 'jordan', isDeveloping: true, countryCode: 'jo', continent: 'asia' },
  { id: 'kz', name: 'カザフスタン', slug: 'kazakhstan', isDeveloping: true, countryCode: 'kz', continent: 'asia' },
  { id: 'kw', name: 'クウェート', slug: 'kuwait', isDeveloping: false, countryCode: 'kw', continent: 'asia' },
  { id: 'kg', name: 'キルギス', slug: 'kyrgyzstan', isDeveloping: true, countryCode: 'kg', continent: 'asia' },
  { id: 'la', name: 'ラオス', slug: 'laos', isDeveloping: true, countryCode: 'la', continent: 'asia' },
  { id: 'lb', name: 'レバノン', slug: 'lebanon', isDeveloping: true, countryCode: 'lb', continent: 'asia' },
  { id: 'my', name: 'マレーシア', slug: 'malaysia', isDeveloping: true, countryCode: 'my', continent: 'asia' },
  { id: 'mv', name: 'モルディブ', slug: 'maldives', isDeveloping: true, countryCode: 'mv', continent: 'asia' },
  { id: 'mn', name: 'モンゴル', slug: 'mongolia', isDeveloping: true, countryCode: 'mn', continent: 'asia' },
  { id: 'mm', name: 'ミャンマー', slug: 'myanmar', isDeveloping: true, countryCode: 'mm', continent: 'asia' },
  { id: 'np', name: 'ネパール', slug: 'nepal', isDeveloping: true, countryCode: 'np', continent: 'asia' },
  { id: 'kp', name: '北朝鮮', slug: 'north-korea', isDeveloping: true, countryCode: 'kp', continent: 'asia' },
  { id: 'om', name: 'オマーン', slug: 'oman', isDeveloping: false, countryCode: 'om', continent: 'asia' },
  { id: 'pk', name: 'パキスタン', slug: 'pakistan', isDeveloping: true, countryCode: 'pk', continent: 'asia' },
  { id: 'ps', name: 'パレスチナ', slug: 'palestine', isDeveloping: true, countryCode: 'ps', continent: 'asia' },
  { id: 'ph', name: 'フィリピン', slug: 'philippines', isDeveloping: true, countryCode: 'ph', continent: 'asia' },
  { id: 'qa', name: 'カタール', slug: 'qatar', isDeveloping: false, countryCode: 'qa', continent: 'asia' },
  { id: 'sa', name: 'サウジアラビア', slug: 'saudi-arabia', isDeveloping: false, countryCode: 'sa', continent: 'asia' },
  { id: 'sg', name: 'シンガポール', slug: 'singapore', isDeveloping: false, countryCode: 'sg', continent: 'asia' },
  { id: 'kr', name: '韓国', slug: 'south-korea', isDeveloping: false, countryCode: 'kr', continent: 'asia' },
  { id: 'lk', name: 'スリランカ', slug: 'sri-lanka', isDeveloping: true, countryCode: 'lk', continent: 'asia' },
  { id: 'sy', name: 'シリア', slug: 'syria', isDeveloping: true, countryCode: 'sy', continent: 'asia' },
  { id: 'tw', name: '台湾', slug: 'taiwan', isDeveloping: false, countryCode: 'tw', continent: 'asia' },
  { id: 'tj', name: 'タジキスタン', slug: 'tajikistan', isDeveloping: true, countryCode: 'tj', continent: 'asia' },
  { id: 'th', name: 'タイ', slug: 'thailand', isDeveloping: true, countryCode: 'th', continent: 'asia' },
  { id: 'tl', name: '東ティモール', slug: 'timor-leste', isDeveloping: true, countryCode: 'tl', continent: 'asia' },
  { id: 'tr', name: 'トルコ', slug: 'turkey', isDeveloping: true, countryCode: 'tr', continent: 'asia' },
  {
    id: 'tm',
    name: 'トルクメニスタン',
    slug: 'turkmenistan',
    isDeveloping: true,
    countryCode: 'tm',
    continent: 'asia',
  },
  {
    id: 'ae',
    name: 'アラブ首長国連邦',
    slug: 'united-arab-emirates',
    isDeveloping: false,
    countryCode: 'ae',
    continent: 'asia',
  },
  { id: 'uz', name: 'ウズベキスタン', slug: 'uzbekistan', isDeveloping: true, countryCode: 'uz', continent: 'asia' },
  { id: 'vn', name: 'ベトナム', slug: 'vietnam', isDeveloping: true, countryCode: 'vn', continent: 'asia' },
  { id: 'ye', name: 'イエメン', slug: 'yemen', isDeveloping: true, countryCode: 'ye', continent: 'asia' },

  // アフリカ
  { id: 'dz', name: 'アルジェリア', slug: 'algeria', isDeveloping: true, countryCode: 'dz', continent: 'africa' },
  { id: 'ao', name: 'アンゴラ', slug: 'angola', isDeveloping: true, countryCode: 'ao', continent: 'africa' },
  { id: 'bj', name: 'ベナン', slug: 'benin', isDeveloping: true, countryCode: 'bj', continent: 'africa' },
  { id: 'bw', name: 'ボツワナ', slug: 'botswana', isDeveloping: true, countryCode: 'bw', continent: 'africa' },
  {
    id: 'bf',
    name: 'ブルキナファソ',
    slug: 'burkina-faso',
    isDeveloping: true,
    countryCode: 'bf',
    continent: 'africa',
  },
  { id: 'bi', name: 'ブルンジ', slug: 'burundi', isDeveloping: true, countryCode: 'bi', continent: 'africa' },
  { id: 'cm', name: 'カメルーン', slug: 'cameroon', isDeveloping: true, countryCode: 'cm', continent: 'africa' },
  { id: 'cv', name: 'カーボベルデ', slug: 'cape-verde', isDeveloping: true, countryCode: 'cv', continent: 'africa' },
  {
    id: 'cf',
    name: '中央アフリカ共和国',
    slug: 'central-african-republic',
    isDeveloping: true,
    countryCode: 'cf',
    continent: 'africa',
  },
  { id: 'td', name: 'チャド', slug: 'chad', isDeveloping: true, countryCode: 'td', continent: 'africa' },
  { id: 'km', name: 'コモロ', slug: 'comoros', isDeveloping: true, countryCode: 'km', continent: 'africa' },
  { id: 'cg', name: 'コンゴ共和国', slug: 'congo', isDeveloping: true, countryCode: 'cg', continent: 'africa' },
  {
    id: 'ci',
    name: 'コートジボワール',
    slug: 'cote-divoire',
    isDeveloping: true,
    countryCode: 'ci',
    continent: 'africa',
  },
  {
    id: 'cd',
    name: 'コンゴ民主共和国',
    slug: 'democratic-republic-of-the-congo',
    isDeveloping: true,
    countryCode: 'cd',
    continent: 'africa',
  },
  { id: 'dj', name: 'ジブチ', slug: 'djibouti', isDeveloping: true, countryCode: 'dj', continent: 'africa' },
  { id: 'eg', name: 'エジプト', slug: 'egypt', isDeveloping: true, countryCode: 'eg', continent: 'africa' },
  {
    id: 'gq',
    name: '赤道ギニア',
    slug: 'equatorial-guinea',
    isDeveloping: true,
    countryCode: 'gq',
    continent: 'africa',
  },
  { id: 'er', name: 'エリトリア', slug: 'eritrea', isDeveloping: true, countryCode: 'er', continent: 'africa' },
  { id: 'et', name: 'エチオピア', slug: 'ethiopia', isDeveloping: true, countryCode: 'et', continent: 'africa' },
  { id: 'ga', name: 'ガボン', slug: 'gabon', isDeveloping: true, countryCode: 'ga', continent: 'africa' },
  { id: 'gm', name: 'ガンビア', slug: 'gambia', isDeveloping: true, countryCode: 'gm', continent: 'africa' },
  { id: 'gh', name: 'ガーナ', slug: 'ghana', isDeveloping: true, countryCode: 'gh', continent: 'africa' },
  { id: 'gn', name: 'ギニア', slug: 'guinea', isDeveloping: true, countryCode: 'gn', continent: 'africa' },
  { id: 'gw', name: 'ギニアビサウ', slug: 'guinea-bissau', isDeveloping: true, countryCode: 'gw', continent: 'africa' },
  { id: 'ke', name: 'ケニア', slug: 'kenya', isDeveloping: true, countryCode: 'ke', continent: 'africa' },
  { id: 'ls', name: 'レソト', slug: 'lesotho', isDeveloping: true, countryCode: 'ls', continent: 'africa' },
  { id: 'lr', name: 'リベリア', slug: 'liberia', isDeveloping: true, countryCode: 'lr', continent: 'africa' },
  { id: 'ly', name: 'リビア', slug: 'libya', isDeveloping: true, countryCode: 'ly', continent: 'africa' },
  { id: 'mg', name: 'マダガスカル', slug: 'madagascar', isDeveloping: true, countryCode: 'mg', continent: 'africa' },
  { id: 'mw', name: 'マラウイ', slug: 'malawi', isDeveloping: true, countryCode: 'mw', continent: 'africa' },
  { id: 'ml', name: 'マリ', slug: 'mali', isDeveloping: true, countryCode: 'ml', continent: 'africa' },
  { id: 'mr', name: 'モーリタニア', slug: 'mauritania', isDeveloping: true, countryCode: 'mr', continent: 'africa' },
  { id: 'mu', name: 'モーリシャス', slug: 'mauritius', isDeveloping: true, countryCode: 'mu', continent: 'africa' },
  { id: 'ma', name: 'モロッコ', slug: 'morocco', isDeveloping: true, countryCode: 'ma', continent: 'africa' },
  { id: 'mz', name: 'モザンビーク', slug: 'mozambique', isDeveloping: true, countryCode: 'mz', continent: 'africa' },
  { id: 'na', name: 'ナミビア', slug: 'namibia', isDeveloping: true, countryCode: 'na', continent: 'africa' },
  { id: 'ne', name: 'ニジェール', slug: 'niger', isDeveloping: true, countryCode: 'ne', continent: 'africa' },
  { id: 'ng', name: 'ナイジェリア', slug: 'nigeria', isDeveloping: true, countryCode: 'ng', continent: 'africa' },
  { id: 'rw', name: 'ルワンダ', slug: 'rwanda', isDeveloping: true, countryCode: 'rw', continent: 'africa' },
  { id: 'sn', name: 'セネガル', slug: 'senegal', isDeveloping: true, countryCode: 'sn', continent: 'africa' },
  { id: 'sc', name: 'セーシェル', slug: 'seychelles', isDeveloping: true, countryCode: 'sc', continent: 'africa' },
  { id: 'sl', name: 'シエラレオネ', slug: 'sierra-leone', isDeveloping: true, countryCode: 'sl', continent: 'africa' },
  { id: 'so', name: 'ソマリア', slug: 'somalia', isDeveloping: true, countryCode: 'so', continent: 'africa' },
  {
    id: 'za',
    name: '南アフリカ共和国',
    slug: 'south-africa',
    isDeveloping: true,
    countryCode: 'za',
    continent: 'africa',
  },
  { id: 'ss', name: '南スーダン', slug: 'south-sudan', isDeveloping: true, countryCode: 'ss', continent: 'africa' },
  { id: 'sd', name: 'スーダン', slug: 'sudan', isDeveloping: true, countryCode: 'sd', continent: 'africa' },
  { id: 'sz', name: 'エスワティニ', slug: 'eswatini', isDeveloping: true, countryCode: 'sz', continent: 'africa' },
  { id: 'tz', name: 'タンザニア', slug: 'tanzania', isDeveloping: true, countryCode: 'tz', continent: 'africa' },
  { id: 'tg', name: 'トーゴ', slug: 'togo', isDeveloping: true, countryCode: 'tg', continent: 'africa' },
  { id: 'tn', name: 'チュニジア', slug: 'tunisia', isDeveloping: true, countryCode: 'tn', continent: 'africa' },
  { id: 'ug', name: 'ウガンダ', slug: 'uganda', isDeveloping: true, countryCode: 'ug', continent: 'africa' },
  { id: 'zm', name: 'ザンビア', slug: 'zambia', isDeveloping: true, countryCode: 'zm', continent: 'africa' },
  { id: 'zw', name: 'ジンバブエ', slug: 'zimbabwe', isDeveloping: true, countryCode: 'zw', continent: 'africa' },

  // ヨーロッパ
  { id: 'al', name: 'アルバニア', slug: 'albania', isDeveloping: true, countryCode: 'al', continent: 'europe' },
  { id: 'ad', name: 'アンドラ', slug: 'andorra', isDeveloping: false, countryCode: 'ad', continent: 'europe' },
  { id: 'at', name: 'オーストリア', slug: 'austria', isDeveloping: false, countryCode: 'at', continent: 'europe' },
  { id: 'by', name: 'ベラルーシ', slug: 'belarus', isDeveloping: true, countryCode: 'by', continent: 'europe' },
  { id: 'be', name: 'ベルギー', slug: 'belgium', isDeveloping: false, countryCode: 'be', continent: 'europe' },
  {
    id: 'ba',
    name: 'ボスニア・ヘルツェゴビナ',
    slug: 'bosnia-and-herzegovina',
    isDeveloping: true,
    countryCode: 'ba',
    continent: 'europe',
  },
  { id: 'bg', name: 'ブルガリア', slug: 'bulgaria', isDeveloping: true, countryCode: 'bg', continent: 'europe' },
  { id: 'hr', name: 'クロアチア', slug: 'croatia', isDeveloping: false, countryCode: 'hr', continent: 'europe' },
  { id: 'cz', name: 'チェコ', slug: 'czech-republic', isDeveloping: false, countryCode: 'cz', continent: 'europe' },
  { id: 'dk', name: 'デンマーク', slug: 'denmark', isDeveloping: false, countryCode: 'dk', continent: 'europe' },
  { id: 'ee', name: 'エストニア', slug: 'estonia', isDeveloping: false, countryCode: 'ee', continent: 'europe' },
  { id: 'fi', name: 'フィンランド', slug: 'finland', isDeveloping: false, countryCode: 'fi', continent: 'europe' },
  { id: 'fr', name: 'フランス', slug: 'france', isDeveloping: false, countryCode: 'fr', continent: 'europe' },
  { id: 'de', name: 'ドイツ', slug: 'germany', isDeveloping: false, countryCode: 'de', continent: 'europe' },
  { id: 'gr', name: 'ギリシャ', slug: 'greece', isDeveloping: false, countryCode: 'gr', continent: 'europe' },
  { id: 'hu', name: 'ハンガリー', slug: 'hungary', isDeveloping: false, countryCode: 'hu', continent: 'europe' },
  { id: 'is', name: 'アイスランド', slug: 'iceland', isDeveloping: false, countryCode: 'is', continent: 'europe' },
  { id: 'ie', name: 'アイルランド', slug: 'ireland', isDeveloping: false, countryCode: 'ie', continent: 'europe' },
  { id: 'it', name: 'イタリア', slug: 'italy', isDeveloping: false, countryCode: 'it', continent: 'europe' },
  { id: 'xk', name: 'コソボ', slug: 'kosovo', isDeveloping: true, countryCode: 'xk', continent: 'europe' },
  { id: 'lv', name: 'ラトビア', slug: 'latvia', isDeveloping: false, countryCode: 'lv', continent: 'europe' },
  {
    id: 'li',
    name: 'リヒテンシュタイン',
    slug: 'liechtenstein',
    isDeveloping: false,
    countryCode: 'li',
    continent: 'europe',
  },
  { id: 'lt', name: 'リトアニア', slug: 'lithuania', isDeveloping: false, countryCode: 'lt', continent: 'europe' },
  { id: 'lu', name: 'ルクセンブルク', slug: 'luxembourg', isDeveloping: false, countryCode: 'lu', continent: 'europe' },
  { id: 'mt', name: 'マルタ', slug: 'malta', isDeveloping: false, countryCode: 'mt', continent: 'europe' },
  { id: 'md', name: 'モルドバ', slug: 'moldova', isDeveloping: true, countryCode: 'md', continent: 'europe' },
  { id: 'mc', name: 'モナコ', slug: 'monaco', isDeveloping: false, countryCode: 'mc', continent: 'europe' },
  { id: 'me', name: 'モンテネグロ', slug: 'montenegro', isDeveloping: true, countryCode: 'me', continent: 'europe' },
  { id: 'nl', name: 'オランダ', slug: 'netherlands', isDeveloping: false, countryCode: 'nl', continent: 'europe' },
  {
    id: 'mk',
    name: '北マケドニア',
    slug: 'north-macedonia',
    isDeveloping: true,
    countryCode: 'mk',
    continent: 'europe',
  },
  { id: 'no', name: 'ノルウェー', slug: 'norway', isDeveloping: false, countryCode: 'no', continent: 'europe' },
  { id: 'pl', name: 'ポーランド', slug: 'poland', isDeveloping: false, countryCode: 'pl', continent: 'europe' },
  { id: 'pt', name: 'ポルトガル', slug: 'portugal', isDeveloping: false, countryCode: 'pt', continent: 'europe' },
  { id: 'ro', name: 'ルーマニア', slug: 'romania', isDeveloping: true, countryCode: 'ro', continent: 'europe' },
  { id: 'ru', name: 'ロシア', slug: 'russia', isDeveloping: true, countryCode: 'ru', continent: 'europe' },
  { id: 'sm', name: 'サンマリノ', slug: 'san-marino', isDeveloping: false, countryCode: 'sm', continent: 'europe' },
  { id: 'rs', name: 'セルビア', slug: 'serbia', isDeveloping: true, countryCode: 'rs', continent: 'europe' },
  { id: 'sk', name: 'スロバキア', slug: 'slovakia', isDeveloping: false, countryCode: 'sk', continent: 'europe' },
  { id: 'si', name: 'スロベニア', slug: 'slovenia', isDeveloping: false, countryCode: 'si', continent: 'europe' },
  { id: 'es', name: 'スペイン', slug: 'spain', isDeveloping: false, countryCode: 'es', continent: 'europe' },
  { id: 'se', name: 'スウェーデン', slug: 'sweden', isDeveloping: false, countryCode: 'se', continent: 'europe' },
  { id: 'ch', name: 'スイス', slug: 'switzerland', isDeveloping: false, countryCode: 'ch', continent: 'europe' },
  { id: 'ua', name: 'ウクライナ', slug: 'ukraine', isDeveloping: true, countryCode: 'ua', continent: 'europe' },
  { id: 'gb', name: 'イギリス', slug: 'united-kingdom', isDeveloping: false, countryCode: 'gb', continent: 'europe' },
  { id: 'va', name: 'バチカン市国', slug: 'vatican-city', isDeveloping: false, countryCode: 'va', continent: 'europe' },

  // 北米
  {
    id: 'ag',
    name: 'アンティグア・バーブーダ',
    slug: 'antigua-and-barbuda',
    isDeveloping: true,
    countryCode: 'ag',
    continent: 'north_america',
  },
  { id: 'bs', name: 'バハマ', slug: 'bahamas', isDeveloping: true, countryCode: 'bs', continent: 'north_america' },
  { id: 'bb', name: 'バルバドス', slug: 'barbados', isDeveloping: true, countryCode: 'bb', continent: 'north_america' },
  { id: 'bz', name: 'ベリーズ', slug: 'belize', isDeveloping: true, countryCode: 'bz', continent: 'north_america' },
  { id: 'ca', name: 'カナダ', slug: 'canada', isDeveloping: false, countryCode: 'ca', continent: 'north_america' },
  {
    id: 'cr',
    name: 'コスタリカ',
    slug: 'costa-rica',
    isDeveloping: true,
    countryCode: 'cr',
    continent: 'north_america',
  },
  { id: 'cu', name: 'キューバ', slug: 'cuba', isDeveloping: true, countryCode: 'cu', continent: 'north_america' },
  { id: 'dm', name: 'ドミニカ国', slug: 'dominica', isDeveloping: true, countryCode: 'dm', continent: 'north_america' },
  {
    id: 'do',
    name: 'ドミニカ共和国',
    slug: 'dominican-republic',
    isDeveloping: true,
    countryCode: 'do',
    continent: 'north_america',
  },
  {
    id: 'sv',
    name: 'エルサルバドル',
    slug: 'el-salvador',
    isDeveloping: true,
    countryCode: 'sv',
    continent: 'north_america',
  },
  { id: 'gd', name: 'グレナダ', slug: 'grenada', isDeveloping: true, countryCode: 'gd', continent: 'north_america' },
  {
    id: 'gt',
    name: 'グアテマラ',
    slug: 'guatemala',
    isDeveloping: true,
    countryCode: 'gt',
    continent: 'north_america',
  },
  { id: 'ht', name: 'ハイチ', slug: 'haiti', isDeveloping: true, countryCode: 'ht', continent: 'north_america' },
  {
    id: 'hn',
    name: 'ホンジュラス',
    slug: 'honduras',
    isDeveloping: true,
    countryCode: 'hn',
    continent: 'north_america',
  },
  { id: 'jm', name: 'ジャマイカ', slug: 'jamaica', isDeveloping: true, countryCode: 'jm', continent: 'north_america' },
  { id: 'mx', name: 'メキシコ', slug: 'mexico', isDeveloping: true, country: 'mx', continent: 'north_america' },
  {
    id: 'ni',
    name: 'ニカラグア',
    slug: 'nicaragua',
    isDeveloping: true,
    countryCode: 'ni',
    continent: 'north_america',
  },
  { id: 'pa', name: 'パナマ', slug: 'panama', isDeveloping: true, countryCode: 'pa', continent: 'north_america' },
  {
    id: 'kn',
    name: 'セントクリストファー・ネイビス',
    slug: 'saint-kitts-and-nevis',
    isDeveloping: true,
    countryCode: 'kn',
    continent: 'north_america',
  },
  {
    id: 'lc',
    name: 'セントルシア',
    slug: 'saint-lucia',
    isDeveloping: true,
    countryCode: 'lc',
    continent: 'north_america',
  },
  {
    id: 'vc',
    name: 'セントビンセント・グレナディーン',
    slug: 'saint-vincent-and-the-grenadines',
    isDeveloping: true,
    countryCode: 'vc',
    continent: 'north_america',
  },
  {
    id: 'tt',
    name: 'トリニダード・トバゴ',
    slug: 'trinidad-and-tobago',
    isDeveloping: true,
    countryCode: 'tt',
    continent: 'north_america',
  },
  {
    id: 'us',
    name: 'アメリカ合衆国',
    slug: 'united-states',
    isDeveloping: false,
    countryCode: 'us',
    continent: 'north_america',
  },

  // 南米
  {
    id: 'ar',
    name: 'アルゼンチン',
    slug: 'argentina',
    isDeveloping: true,
    countryCode: 'ar',
    continent: 'south_america',
  },
  { id: 'bo', name: 'ボリビア', slug: 'bolivia', isDeveloping: true, countryCode: 'bo', continent: 'south_america' },
  { id: 'br', name: 'ブラジル', slug: 'brazil', isDeveloping: true, countryCode: 'br', continent: 'south_america' },
  { id: 'cl', name: 'チリ', slug: 'chile', isDeveloping: true, countryCode: 'cl', continent: 'south_america' },
  { id: 'co', name: 'コロンビア', slug: 'colombia', isDeveloping: true, countryCode: 'co', continent: 'south_america' },
  { id: 'ec', name: 'エクアドル', slug: 'ecuador', isDeveloping: true, countryCode: 'ec', continent: 'south_america' },
  { id: 'gy', name: 'ガイアナ', slug: 'guyana', isDeveloping: true, countryCode: 'gy', continent: 'south_america' },
  { id: 'py', name: 'パラグアイ', slug: 'paraguay', isDeveloping: true, countryCode: 'py', continent: 'south_america' },
  { id: 'pe', name: 'ペルー', slug: 'peru', isDeveloping: true, countryCode: 'pe', continent: 'south_america' },
  { id: 'sr', name: 'スリナム', slug: 'suriname', isDeveloping: true, countryCode: 'sr', continent: 'south_america' },
  { id: 'uy', name: 'ウルグアイ', slug: 'uruguay', isDeveloping: true, countryCode: 'uy', continent: 'south_america' },
  {
    id: 've',
    name: 'ベネズエラ',
    slug: 'venezuela',
    isDeveloping: true,
    countryCode: 've',
    continent: 'south_america',
  },

  // オセアニア
  { id: 'au', name: 'オーストラリア', slug: 'australia', isDeveloping: false, countryCode: 'au', continent: 'oceania' },
  { id: 'fj', name: 'フィジー', slug: 'fiji', isDeveloping: true, countryCode: 'fj', continent: 'oceania' },
  { id: 'ki', name: 'キリバス', slug: 'kiribati', isDeveloping: true, countryCode: 'ki', continent: 'oceania' },
  {
    id: 'mh',
    name: 'マーシャル諸島',
    slug: 'marshall-islands',
    isDeveloping: true,
    countryCode: 'mh',
    continent: 'oceania',
  },
  {
    id: 'fm',
    name: 'ミクロネシア連邦',
    slug: 'micronesia',
    isDeveloping: true,
    countryCode: 'fm',
    continent: 'oceania',
  },
  { id: 'nr', name: 'ナウル', slug: 'nauru', isDeveloping: true, countryCode: 'nr', continent: 'oceania' },
  {
    id: 'nz',
    name: 'ニュージーランド',
    slug: 'new-zealand',
    isDeveloping: false,
    countryCode: 'nz',
    continent: 'oceania',
  },
  { id: 'pw', name: 'パラオ', slug: 'palau', isDeveloping: true, countryCode: 'pw', continent: 'oceania' },
  {
    id: 'pg',
    name: 'パプアニューギニア',
    slug: 'papua-new-guinea',
    isDeveloping: true,
    countryCode: 'pg',
    continent: 'oceania',
  },
  { id: 'ws', name: 'サモア', slug: 'samoa', isDeveloping: true, countryCode: 'ws', continent: 'oceania' },
  {
    id: 'sb',
    name: 'ソロモン諸島',
    slug: 'solomon-islands',
    isDeveloping: true,
    countryCode: 'sb',
    continent: 'oceania',
  },
  { id: 'to', name: 'トンガ', slug: 'tonga', isDeveloping: true, countryCode: 'to', continent: 'oceania' },
  { id: 'tv', name: 'ツバル', slug: 'tuvalu', isDeveloping: true, countryCode: 'tv', continent: 'oceania' },
  { id: 'vu', name: 'バヌアツ', slug: 'vanuatu', isDeveloping: true, countryCode: 'vu', continent: 'oceania' },
];
