export const regions = [
  { id: 1, name: 'アフリカ', slug: 'africa' },
  { id: 2, name: 'アジア', slug: 'asia' },
  { id: 3, name: 'ヨーロッパ', slug: 'europe' },
  { id: 4, name: '北米', slug: 'north-america' },
  { id: 5, name: '南米', slug: 'south-america' },
  { id: 6, name: 'オセアニア', slug: 'oceania' },
  { id: 7, name: '中東', slug: 'middle-east' },
  { id: 8, name: '中央アメリカ', slug: 'central-america' },
  { id: 9, name: 'カリブ海', slug: 'caribbean' },
];

export const countries = [
  // アフリカ (id: 1)
  { id: 1, name: 'アルジェリア', slug: 'algeria', regionId: 1 },
  { id: 2, name: 'アンゴラ', slug: 'angola', regionId: 1 },
  { id: 3, name: 'ベナン', slug: 'benin', regionId: 1 },
  { id: 4, name: 'ボツワナ', slug: 'botswana', regionId: 1 },
  { id: 5, name: 'ブルキナファソ', slug: 'burkina-faso', regionId: 1 },
  { id: 6, name: 'ブルンジ', slug: 'burundi', regionId: 1 },
  { id: 7, name: 'カメルーン', slug: 'cameroon', regionId: 1 },
  { id: 8, name: 'カーボベルデ', slug: 'cape-verde', regionId: 1 },
  { id: 9, name: '中央アフリカ共和国', slug: 'central-african-republic', regionId: 1 },
  { id: 10, name: 'チャド', slug: 'chad', regionId: 1 },
  { id: 11, name: 'コモロ', slug: 'comoros', regionId: 1 },
  { id: 12, name: 'コンゴ共和国', slug: 'republic-of-congo', regionId: 1 },
  { id: 13, name: 'コンゴ民主共和国', slug: 'democratic-republic-of-congo', regionId: 1 },
  { id: 14, name: 'ジブチ', slug: 'djibouti', regionId: 1 },
  { id: 15, name: 'エジプト', slug: 'egypt', regionId: 1 },
  { id: 16, name: '赤道ギニア', slug: 'equatorial-guinea', regionId: 1 },
  { id: 17, name: 'エリトリア', slug: 'eritrea', regionId: 1 },
  { id: 18, name: 'エスワティニ', slug: 'eswatini', regionId: 1 },
  { id: 19, name: 'エチオピア', slug: 'ethiopia', regionId: 1 },
  { id: 20, name: 'ガボン', slug: 'gabon', regionId: 1 },
  { id: 21, name: 'ガンビア', slug: 'gambia', regionId: 1 },
  { id: 22, name: 'ガーナ', slug: 'ghana', regionId: 1 },
  { id: 23, name: 'ギニア', slug: 'guinea', regionId: 1 },
  { id: 24, name: 'ギニアビサウ', slug: 'guinea-bissau', regionId: 1 },
  { id: 25, name: 'コートジボワール', slug: 'ivory-coast', regionId: 1 },
  { id: 26, name: 'ケニア', slug: 'kenya', regionId: 1 },
  { id: 27, name: 'レソト', slug: 'lesotho', regionId: 1 },
  { id: 28, name: 'リベリア', slug: 'liberia', regionId: 1 },
  { id: 29, name: 'リビア', slug: 'libya', regionId: 1 },
  { id: 30, name: 'マダガスカル', slug: 'madagascar', regionId: 1 },
  { id: 31, name: 'マラウイ', slug: 'malawi', regionId: 1 },
  { id: 32, name: 'マリ', slug: 'mali', regionId: 1 },
  { id: 33, name: 'モーリタニア', slug: 'mauritania', regionId: 1 },
  { id: 34, name: 'モーリシャス', slug: 'mauritius', regionId: 1 },
  { id: 35, name: 'モロッコ', slug: 'morocco', regionId: 1 },
  { id: 36, name: 'モザンビーク', slug: 'mozambique', regionId: 1 },
  { id: 37, name: 'ナミビア', slug: 'namibia', regionId: 1 },
  { id: 38, name: 'ニジェール', slug: 'niger', regionId: 1 },
  { id: 39, name: 'ナイジェリア', slug: 'nigeria', regionId: 1 },
  { id: 40, name: 'ルワンダ', slug: 'rwanda', regionId: 1 },
  { id: 41, name: 'サントメ・プリンシペ', slug: 'sao-tome-and-principe', regionId: 1 },
  { id: 42, name: 'セネガル', slug: 'senegal', regionId: 1 },
  { id: 43, name: 'セーシェル', slug: 'seychelles', regionId: 1 },
  { id: 44, name: 'シエラレオネ', slug: 'sierra-leone', regionId: 1 },
  { id: 45, name: 'ソマリア', slug: 'somalia', regionId: 1 },
  { id: 46, name: '南アフリカ', slug: 'south-africa', regionId: 1 },
  { id: 47, name: '南スーダン', slug: 'south-sudan', regionId: 1 },
  { id: 48, name: 'スーダン', slug: 'sudan', regionId: 1 },
  { id: 49, name: 'タンザニア', slug: 'tanzania', regionId: 1 },
  { id: 50, name: 'トーゴ', slug: 'togo', regionId: 1 },
  { id: 51, name: 'チュニジア', slug: 'tunisia', regionId: 1 },
  { id: 52, name: 'ウガンダ', slug: 'uganda', regionId: 1 },
  { id: 53, name: 'ザンビア', slug: 'zambia', regionId: 1 },
  { id: 54, name: 'ジンバブエ', slug: 'zimbabwe', regionId: 1 },

  // アジア (id: 2)
  { id: 55, name: 'アフガニスタン', slug: 'afghanistan', regionId: 2 },
  { id: 56, name: 'バングラデシュ', slug: 'bangladesh', regionId: 2 },
  { id: 57, name: 'ブータン', slug: 'bhutan', regionId: 2 },
  { id: 58, name: 'ブルネイ', slug: 'brunei', regionId: 2 },
  { id: 59, name: 'カンボジア', slug: 'cambodia', regionId: 2 },
  { id: 60, name: '中国', slug: 'china', regionId: 2 },
  { id: 61, name: 'インド', slug: 'india', regionId: 2 },
  { id: 62, name: 'インドネシア', slug: 'indonesia', regionId: 2 },
  { id: 63, name: '日本', slug: 'japan', regionId: 2 },
  { id: 64, name: 'カザフスタン', slug: 'kazakhstan', regionId: 2 },
  { id: 65, name: '北朝鮮', slug: 'north-korea', regionId: 2 },
  { id: 66, name: '韓国', slug: 'south-korea', regionId: 2 },
  { id: 67, name: 'キルギス', slug: 'kyrgyzstan', regionId: 2 },
  { id: 68, name: 'ラオス', slug: 'laos', regionId: 2 },
  { id: 69, name: 'マレーシア', slug: 'malaysia', regionId: 2 },
  { id: 70, name: 'モルディブ', slug: 'maldives', regionId: 2 },
  { id: 71, name: 'モンゴル', slug: 'mongolia', regionId: 2 },
  { id: 72, name: 'ミャンマー', slug: 'myanmar', regionId: 2 },
  { id: 73, name: 'ネパール', slug: 'nepal', regionId: 2 },
  { id: 74, name: 'パキスタン', slug: 'pakistan', regionId: 2 },
  { id: 75, name: 'フィリピン', slug: 'philippines', regionId: 2 },
  { id: 76, name: 'シンガポール', slug: 'singapore', regionId: 2 },
  { id: 77, name: 'スリランカ', slug: 'sri-lanka', regionId: 2 },
  { id: 78, name: '台湾', slug: 'taiwan', regionId: 2 },
  { id: 79, name: 'タジキスタン', slug: 'tajikistan', regionId: 2 },
  { id: 80, name: 'タイ', slug: 'thailand', regionId: 2 },
  { id: 81, name: '東ティモール', slug: 'east-timor', regionId: 2 },
  { id: 82, name: 'トルクメニスタン', slug: 'turkmenistan', regionId: 2 },
  { id: 83, name: 'ウズベキスタン', slug: 'uzbekistan', regionId: 2 },
  { id: 84, name: 'ベトナム', slug: 'vietnam', regionId: 2 },

  // ヨーロッパ (id: 3)
  { id: 85, name: 'アルバニア', slug: 'albania', regionId: 3 },
  { id: 86, name: 'アンドラ', slug: 'andorra', regionId: 3 },
  { id: 87, name: 'オーストリア', slug: 'austria', regionId: 3 },
  { id: 88, name: 'ベラルーシ', slug: 'belarus', regionId: 3 },
  { id: 89, name: 'ベルギー', slug: 'belgium', regionId: 3 },
  { id: 90, name: 'ボスニア・ヘルツェゴビナ', slug: 'bosnia-and-herzegovina', regionId: 3 },
  { id: 91, name: 'ブルガリア', slug: 'bulgaria', regionId: 3 },
  { id: 92, name: 'クロアチア', slug: 'croatia', regionId: 3 },
  { id: 93, name: 'チェコ', slug: 'czech-republic', regionId: 3 },
  { id: 94, name: 'デンマーク', slug: 'denmark', regionId: 3 },
  { id: 95, name: 'エストニア', slug: 'estonia', regionId: 3 },
  { id: 96, name: 'フィンランド', slug: 'finland', regionId: 3 },
  { id: 97, name: 'フランス', slug: 'france', regionId: 3 },
  { id: 98, name: 'ドイツ', slug: 'germany', regionId: 3 },
  { id: 99, name: 'ギリシャ', slug: 'greece', regionId: 3 },
  { id: 100, name: 'ハンガリー', slug: 'hungary', regionId: 3 },
  { id: 101, name: 'アイスランド', slug: 'iceland', regionId: 3 },
  { id: 102, name: 'アイルランド', slug: 'ireland', regionId: 3 },
  { id: 103, name: 'イタリア', slug: 'italy', regionId: 3 },
  { id: 104, name: 'コソボ', slug: 'kosovo', regionId: 3 },
  { id: 105, name: 'ラトビア', slug: 'latvia', regionId: 3 },
  { id: 106, name: 'リヒテンシュタイン', slug: 'liechtenstein', regionId: 3 },
  { id: 107, name: 'リトアニア', slug: 'lithuania', regionId: 3 },
  { id: 108, name: 'ルクセンブルク', slug: 'luxembourg', regionId: 3 },
  { id: 109, name: 'マルタ', slug: 'malta', regionId: 3 },
  { id: 110, name: 'モルドバ', slug: 'moldova', regionId: 3 },
  { id: 111, name: 'モナコ', slug: 'monaco', regionId: 3 },
  { id: 112, name: 'モンテネグロ', slug: 'montenegro', regionId: 3 },
  { id: 113, name: 'オランダ', slug: 'netherlands', regionId: 3 },
  // ヨーロッパ (id: 3) の続き
  { id: 114, name: '北マケドニア', slug: 'north-macedonia', regionId: 3 },
  { id: 115, name: 'ノルウェー', slug: 'norway', regionId: 3 },
  { id: 116, name: 'ポーランド', slug: 'poland', regionId: 3 },
  { id: 117, name: 'ポルトガル', slug: 'portugal', regionId: 3 },
  { id: 118, name: 'ルーマニア', slug: 'romania', regionId: 3 },
  { id: 119, name: 'ロシア', slug: 'russia', regionId: 3 },
  { id: 120, name: 'サンマリノ', slug: 'san-marino', regionId: 3 },
  { id: 121, name: 'セルビア', slug: 'serbia', regionId: 3 },
  { id: 122, name: 'スロバキア', slug: 'slovakia', regionId: 3 },
  { id: 123, name: 'スロベニア', slug: 'slovenia', regionId: 3 },
  { id: 124, name: 'スペイン', slug: 'spain', regionId: 3 },
  { id: 125, name: 'スウェーデン', slug: 'sweden', regionId: 3 },
  { id: 126, name: 'スイス', slug: 'switzerland', regionId: 3 },
  { id: 127, name: 'ウクライナ', slug: 'ukraine', regionId: 3 },
  { id: 128, name: 'イギリス', slug: 'united-kingdom', regionId: 3 },
  { id: 129, name: 'バチカン市国', slug: 'vatican-city', regionId: 3 },

  // 北米 (id: 4)
  { id: 130, name: 'カナダ', slug: 'canada', regionId: 4 },
  { id: 131, name: 'メキシコ', slug: 'mexico', regionId: 4 },
  { id: 132, name: 'アメリカ合衆国', slug: 'united-states', regionId: 4 },

  // 南米 (id: 5)
  { id: 133, name: 'アルゼンチン', slug: 'argentina', regionId: 5 },
  { id: 134, name: 'ボリビア', slug: 'bolivia', regionId: 5 },
  { id: 135, name: 'ブラジル', slug: 'brazil', regionId: 5 },
  { id: 136, name: 'チリ', slug: 'chile', regionId: 5 },
  { id: 137, name: 'コロンビア', slug: 'colombia', regionId: 5 },
  { id: 138, name: 'エクアドル', slug: 'ecuador', regionId: 5 },
  { id: 139, name: 'ガイアナ', slug: 'guyana', regionId: 5 },
  { id: 140, name: 'パラグアイ', slug: 'paraguay', regionId: 5 },
  { id: 141, name: 'ペルー', slug: 'peru', regionId: 5 },
  { id: 142, name: 'スリナム', slug: 'suriname', regionId: 5 },
  { id: 143, name: 'ウルグアイ', slug: 'uruguay', regionId: 5 },
  { id: 144, name: 'ベネズエラ', slug: 'venezuela', regionId: 5 },

  // オセアニア (id: 6)
  { id: 145, name: 'オーストラリア', slug: 'australia', regionId: 6 },
  { id: 146, name: 'フィジー', slug: 'fiji', regionId: 6 },
  { id: 147, name: 'キリバス', slug: 'kiribati', regionId: 6 },
  { id: 148, name: 'マーシャル諸島', slug: 'marshall-islands', regionId: 6 },
  { id: 149, name: 'ミクロネシア', slug: 'micronesia', regionId: 6 },
  { id: 150, name: 'ナウル', slug: 'nauru', regionId: 6 },
  { id: 151, name: 'ニュージーランド', slug: 'new-zealand', regionId: 6 },
  { id: 152, name: 'パラオ', slug: 'palau', regionId: 6 },
  { id: 153, name: 'パプアニューギニア', slug: 'papua-new-guinea', regionId: 6 },
  { id: 154, name: 'サモア', slug: 'samoa', regionId: 6 },
  { id: 155, name: 'ソロモン諸島', slug: 'solomon-islands', regionId: 6 },
  { id: 156, name: 'トンガ', slug: 'tonga', regionId: 6 },
  { id: 157, name: 'ツバル', slug: 'tuvalu', regionId: 6 },
  { id: 158, name: 'バヌアツ', slug: 'vanuatu', regionId: 6 },

  // 中東 (id: 7)
  { id: 159, name: 'バーレーン', slug: 'bahrain', regionId: 7 },
  { id: 160, name: 'キプロス', slug: 'cyprus', regionId: 7 },
  { id: 161, name: 'イラン', slug: 'iran', regionId: 7 },
  { id: 162, name: 'イラク', slug: 'iraq', regionId: 7 },
  { id: 163, name: 'イスラエル', slug: 'israel', regionId: 7 },
  { id: 164, name: 'ヨルダン', slug: 'jordan', regionId: 7 },
  { id: 165, name: 'クウェート', slug: 'kuwait', regionId: 7 },
  { id: 166, name: 'レバノン', slug: 'lebanon', regionId: 7 },
  { id: 167, name: 'オマーン', slug: 'oman', regionId: 7 },
  { id: 168, name: 'パレスチナ', slug: 'palestine', regionId: 7 },
  { id: 169, name: 'カタール', slug: 'qatar', regionId: 7 },
  { id: 170, name: 'サウジアラビア', slug: 'saudi-arabia', regionId: 7 },
  { id: 171, name: 'シリア', slug: 'syria', regionId: 7 },
  { id: 172, name: 'トルコ', slug: 'turkey', regionId: 7 },
  { id: 173, name: 'アラブ首長国連邦', slug: 'united-arab-emirates', regionId: 7 },
  { id: 174, name: 'イエメン', slug: 'yemen', regionId: 7 },

  // 中央アメリカ (id: 8)
  { id: 175, name: 'ベリーズ', slug: 'belize', regionId: 8 },
  { id: 176, name: 'コスタリカ', slug: 'costa-rica', regionId: 8 },
  { id: 177, name: 'エルサルバドル', slug: 'el-salvador', regionId: 8 },
  { id: 178, name: 'グアテマラ', slug: 'guatemala', regionId: 8 },
  { id: 179, name: 'ホンジュラス', slug: 'honduras', regionId: 8 },
  { id: 180, name: 'ニカラグア', slug: 'nicaragua', regionId: 8 },
  { id: 181, name: 'パナマ', slug: 'panama', regionId: 8 },

  // カリブ海 (id: 9)
  { id: 182, name: 'アンティグア・バーブーダ', slug: 'antigua-and-barbuda', regionId: 9 },
  { id: 183, name: 'バハマ', slug: 'bahamas', regionId: 9 },
  { id: 184, name: 'バルバドス', slug: 'barbados', regionId: 9 },
  { id: 185, name: 'キューバ', slug: 'cuba', regionId: 9 },
  { id: 186, name: 'ドミニカ国', slug: 'dominica', regionId: 9 },
  { id: 187, name: 'ドミニカ共和国', slug: 'dominican-republic', regionId: 9 },
  { id: 188, name: 'グレナダ', slug: 'grenada', regionId: 9 },
  { id: 189, name: 'ハイチ', slug: 'haiti', regionId: 9 },
  { id: 190, name: 'ジャマイカ', slug: 'jamaica', regionId: 9 },
  { id: 191, name: 'セントクリストファー・ネイビス', slug: 'saint-kitts-and-nevis', regionId: 9 },
  { id: 192, name: 'セントルシア', slug: 'saint-lucia', regionId: 9 },
  { id: 193, name: 'セントビンセント・グレナディーン', slug: 'saint-vincent-and-the-grenadines', regionId: 9 },
  { id: 194, name: 'トリニダード・トバゴ', slug: 'trinidad-and-tobago', regionId: 9 },
];
