export const COUNTRIES = [
  // アジア
  { id: 'AF', name: 'アフガニスタン', slug: 'afghanistan', isDeveloping: true, countryCode: 'af', continent: 'asia' },
  { id: 'AM', name: 'アルメニア', slug: 'armenia', isDeveloping: true, countryCode: 'am', continent: 'asia' },
  { id: 'AZ', name: 'アゼルバイジャン', slug: 'azerbaijan', isDeveloping: true, countryCode: 'az', continent: 'asia' },
  { id: 'BH', name: 'バーレーン', slug: 'bahrain', isDeveloping: false, countryCode: 'bh', continent: 'asia' },
  { id: 'BD', name: 'バングラデシュ', slug: 'bangladesh', isDeveloping: true, countryCode: 'bd', continent: 'asia' },
  { id: 'BT', name: 'ブータン', slug: 'bhutan', isDeveloping: true, countryCode: 'bt', continent: 'asia' },
  { id: 'BN', name: 'ブルネイ', slug: 'brunei', isDeveloping: false, countryCode: 'bn', continent: 'asia' },
  { id: 'KH', name: 'カンボジア', slug: 'cambodia', isDeveloping: true, countryCode: 'kh', continent: 'asia' },
  { id: 'CN', name: '中国', slug: 'china', isDeveloping: true, countryCode: 'cn', continent: 'asia' },
  { id: 'CY', name: 'キプロス', slug: 'cyprus', isDeveloping: false, countryCode: 'cy', continent: 'asia' },
  { id: 'GE', name: 'ジョージア', slug: 'georgia', isDeveloping: true, countryCode: 'ge', continent: 'asia' },
  { id: 'IN', name: 'インド', slug: 'india', isDeveloping: true, countryCode: 'in', continent: 'asia' },
  { id: 'ID', name: 'インドネシア', slug: 'indonesia', isDeveloping: true, countryCode: 'id', continent: 'asia' },
  { id: 'IR', name: 'イラン', slug: 'iran', isDeveloping: true, countryCode: 'ir', continent: 'asia' },
  { id: 'IQ', name: 'イラク', slug: 'iraq', isDeveloping: true, countryCode: 'iq', continent: 'asia' },
  { id: 'IL', name: 'イスラエル', slug: 'israel', isDeveloping: false, countryCode: 'il', continent: 'asia' },
  { id: 'JP', name: '日本', slug: 'japan', isDeveloping: false, countryCode: 'jp', continent: 'asia' },
  { id: 'JO', name: 'ヨルダン', slug: 'jordan', isDeveloping: true, countryCode: 'jo', continent: 'asia' },
  { id: 'KZ', name: 'カザフスタン', slug: 'kazakhstan', isDeveloping: true, countryCode: 'kz', continent: 'asia' },
  { id: 'KW', name: 'クウェート', slug: 'kuwait', isDeveloping: false, countryCode: 'kw', continent: 'asia' },
  { id: 'KG', name: 'キルギス', slug: 'kyrgyzstan', isDeveloping: true, countryCode: 'kg', continent: 'asia' },
  { id: 'LA', name: 'ラオス', slug: 'laos', isDeveloping: true, countryCode: 'la', continent: 'asia' },
  { id: 'LB', name: 'レバノン', slug: 'lebanon', isDeveloping: true, countryCode: 'lb', continent: 'asia' },
  { id: 'MY', name: 'マレーシア', slug: 'malaysia', isDeveloping: true, countryCode: 'my', continent: 'asia' },
  { id: 'MV', name: 'モルディブ', slug: 'maldives', isDeveloping: true, countryCode: 'mv', continent: 'asia' },
  { id: 'MN', name: 'モンゴル', slug: 'mongolia', isDeveloping: true, countryCode: 'mn', continent: 'asia' },
  { id: 'MM', name: 'ミャンマー', slug: 'myanmar', isDeveloping: true, countryCode: 'mm', continent: 'asia' },
  { id: 'NP', name: 'ネパール', slug: 'nepal', isDeveloping: true, countryCode: 'np', continent: 'asia' },
  { id: 'KP', name: '北朝鮮', slug: 'north-korea', isDeveloping: true, countryCode: 'kp', continent: 'asia' },
  { id: 'OM', name: 'オマーン', slug: 'oman', isDeveloping: false, countryCode: 'om', continent: 'asia' },
  { id: 'PK', name: 'パキスタン', slug: 'pakistan', isDeveloping: true, countryCode: 'pk', continent: 'asia' },
  { id: 'PS', name: 'パレスチナ', slug: 'palestine', isDeveloping: true, countryCode: 'ps', continent: 'asia' },
  { id: 'PH', name: 'フィリピン', slug: 'philippines', isDeveloping: true, countryCode: 'ph', continent: 'asia' },
  { id: 'QA', name: 'カタール', slug: 'qatar', isDeveloping: false, countryCode: 'qa', continent: 'asia' },
  { id: 'SA', name: 'サウジアラビア', slug: 'saudi-arabia', isDeveloping: false, countryCode: 'sa', continent: 'asia' },
  { id: 'SG', name: 'シンガポール', slug: 'singapore', isDeveloping: false, countryCode: 'sg', continent: 'asia' },
  { id: 'KR', name: '韓国', slug: 'south-korea', isDeveloping: false, countryCode: 'kr', continent: 'asia' },
  { id: 'LK', name: 'スリランカ', slug: 'sri-lanka', isDeveloping: true, countryCode: 'lk', continent: 'asia' },
  { id: 'SY', name: 'シリア', slug: 'syria', isDeveloping: true, countryCode: 'sy', continent: 'asia' },
  { id: 'TW', name: '台湾', slug: 'taiwan', isDeveloping: false, countryCode: 'tw', continent: 'asia' },
  { id: 'TJ', name: 'タジキスタン', slug: 'tajikistan', isDeveloping: true, countryCode: 'tj', continent: 'asia' },
  { id: 'TH', name: 'タイ', slug: 'thailand', isDeveloping: true, countryCode: 'th', continent: 'asia' },
  { id: 'TL', name: '東ティモール', slug: 'timor-leste', isDeveloping: true, countryCode: 'tl', continent: 'asia' },
  { id: 'TR', name: 'トルコ', slug: 'turkey', isDeveloping: true, countryCode: 'tr', continent: 'asia' },
  {
    id: 'TM',
    name: 'トルクメニスタン',
    slug: 'turkmenistan',
    isDeveloping: true,
    countryCode: 'tm',
    continent: 'asia',
  },
  {
    id: 'AE',
    name: 'アラブ首長国連邦',
    slug: 'united-arab-emirates',
    isDeveloping: false,
    countryCode: 'ae',
    continent: 'asia',
  },
  { id: 'UZ', name: 'ウズベキスタン', slug: 'uzbekistan', isDeveloping: true, countryCode: 'uz', continent: 'asia' },
  { id: 'VN', name: 'ベトナム', slug: 'vietnam', isDeveloping: true, countryCode: 'vn', continent: 'asia' },
  { id: 'YE', name: 'イエメン', slug: 'yemen', isDeveloping: true, countryCode: 'ye', continent: 'asia' },

  // アフリカ
  { id: 'DZ', name: 'アルジェリア', slug: 'algeria', isDeveloping: true, countryCode: 'dz', continent: 'africa' },
  { id: 'AO', name: 'アンゴラ', slug: 'angola', isDeveloping: true, countryCode: 'ao', continent: 'africa' },
  { id: 'BJ', name: 'ベナン', slug: 'benin', isDeveloping: true, countryCode: 'bj', continent: 'africa' },
  { id: 'BW', name: 'ボツワナ', slug: 'botswana', isDeveloping: true, countryCode: 'bw', continent: 'africa' },
  {
    id: 'BF',
    name: 'ブルキナファソ',
    slug: 'burkina-faso',
    isDeveloping: true,
    countryCode: 'bf',
    continent: 'africa',
  },
  { id: 'BI', name: 'ブルンジ', slug: 'burundi', isDeveloping: true, countryCode: 'bi', continent: 'africa' },
  { id: 'CM', name: 'カメルーン', slug: 'cameroon', isDeveloping: true, countryCode: 'cm', continent: 'africa' },
  { id: 'CV', name: 'カーボベルデ', slug: 'cape-verde', isDeveloping: true, countryCode: 'cv', continent: 'africa' },
  {
    id: 'CF',
    name: '中央アフリカ共和国',
    slug: 'central-african-republic',
    isDeveloping: true,
    countryCode: 'cf',
    continent: 'africa',
  },
  { id: 'TD', name: 'チャド', slug: 'chad', isDeveloping: true, countryCode: 'td', continent: 'africa' },
  { id: 'KM', name: 'コモロ', slug: 'comoros', isDeveloping: true, countryCode: 'km', continent: 'africa' },
  { id: 'CG', name: 'コンゴ共和国', slug: 'congo', isDeveloping: true, countryCode: 'cg', continent: 'africa' },
  {
    id: 'CI',
    name: 'コートジボワール',
    slug: 'cote-divoire',
    isDeveloping: true,
    countryCode: 'ci',
    continent: 'africa',
  },
  {
    id: 'CD',
    name: 'コンゴ民主共和国',
    slug: 'democratic-republic-of-the-congo',
    isDeveloping: true,
    countryCode: 'cd',
    continent: 'africa',
  },
  { id: 'DJ', name: 'ジブチ', slug: 'djibouti', isDeveloping: true, countryCode: 'dj', continent: 'africa' },
  { id: 'EG', name: 'エジプト', slug: 'egypt', isDeveloping: true, countryCode: 'eg', continent: 'africa' },
  {
    id: 'GQ',
    name: '赤道ギニア',
    slug: 'equatorial-guinea',
    isDeveloping: true,
    countryCode: 'gq',
    continent: 'africa',
  },
  { id: 'ER', name: 'エリトリア', slug: 'eritrea', isDeveloping: true, countryCode: 'er', continent: 'africa' },
  { id: 'ET', name: 'エチオピア', slug: 'ethiopia', isDeveloping: true, countryCode: 'et', continent: 'africa' },
  { id: 'GA', name: 'ガボン', slug: 'gabon', isDeveloping: true, countryCode: 'ga', continent: 'africa' },
  { id: 'GM', name: 'ガンビア', slug: 'gambia', isDeveloping: true, countryCode: 'gm', continent: 'africa' },
  { id: 'GH', name: 'ガーナ', slug: 'ghana', isDeveloping: true, countryCode: 'gh', continent: 'africa' },
  { id: 'GN', name: 'ギニア', slug: 'guinea', isDeveloping: true, countryCode: 'gn', continent: 'africa' },
  { id: 'GW', name: 'ギニアビサウ', slug: 'guinea-bissau', isDeveloping: true, countryCode: 'gw', continent: 'africa' },
  { id: 'KE', name: 'ケニア', slug: 'kenya', isDeveloping: true, countryCode: 'ke', continent: 'africa' },
  { id: 'LS', name: 'レソト', slug: 'lesotho', isDeveloping: true, countryCode: 'ls', continent: 'africa' },
  { id: 'LR', name: 'リベリア', slug: 'liberia', isDeveloping: true, countryCode: 'lr', continent: 'africa' },
  { id: 'LY', name: 'リビア', slug: 'libya', isDeveloping: true, countryCode: 'ly', continent: 'africa' },
  { id: 'MG', name: 'マダガスカル', slug: 'madagascar', isDeveloping: true, countryCode: 'mg', continent: 'africa' },
  { id: 'MW', name: 'マラウイ', slug: 'malawi', isDeveloping: true, countryCode: 'mw', continent: 'africa' },
  { id: 'ML', name: 'マリ', slug: 'mali', isDeveloping: true, countryCode: 'ml', continent: 'africa' },
  { id: 'MR', name: 'モーリタニア', slug: 'mauritania', isDeveloping: true, countryCode: 'mr', continent: 'africa' },
  { id: 'MU', name: 'モーリシャス', slug: 'mauritius', isDeveloping: true, countryCode: 'mu', continent: 'africa' },
  { id: 'MA', name: 'モロッコ', slug: 'morocco', isDeveloping: true, countryCode: 'ma', continent: 'africa' },
  { id: 'MZ', name: 'モザンビーク', slug: 'mozambique', isDeveloping: true, countryCode: 'mz', continent: 'africa' },
  { id: 'NA', name: 'ナミビア', slug: 'namibia', isDeveloping: true, countryCode: 'na', continent: 'africa' },
  { id: 'NE', name: 'ニジェール', slug: 'niger', isDeveloping: true, countryCode: 'ne', continent: 'africa' },
  { id: 'NG', name: 'ナイジェリア', slug: 'nigeria', isDeveloping: true, countryCode: 'ng', continent: 'africa' },
  { id: 'RW', name: 'ルワンダ', slug: 'rwanda', isDeveloping: true, countryCode: 'rw', continent: 'africa' },
  { id: 'SN', name: 'セネガル', slug: 'senegal', isDeveloping: true, countryCode: 'sn', continent: 'africa' },
  { id: 'SC', name: 'セーシェル', slug: 'seychelles', isDeveloping: true, countryCode: 'sc', continent: 'africa' },
  { id: 'SL', name: 'シエラレオネ', slug: 'sierra-leone', isDeveloping: true, countryCode: 'sl', continent: 'africa' },
  { id: 'SO', name: 'ソマリア', slug: 'somalia', isDeveloping: true, countryCode: 'so', continent: 'africa' },
  {
    id: 'ZA',
    name: '南アフリカ共和国',
    slug: 'south-africa',
    isDeveloping: true,
    countryCode: 'za',
    continent: 'africa',
  },
  { id: 'SS', name: '南スーダン', slug: 'south-sudan', isDeveloping: true, countryCode: 'ss', continent: 'africa' },
  { id: 'SD', name: 'スーダン', slug: 'sudan', isDeveloping: true, countryCode: 'sd', continent: 'africa' },
  { id: 'SZ', name: 'エスワティニ', slug: 'eswatini', isDeveloping: true, countryCode: 'sz', continent: 'africa' },
  { id: 'TZ', name: 'タンザニア', slug: 'tanzania', isDeveloping: true, countryCode: 'tz', continent: 'africa' },
  { id: 'TG', name: 'トーゴ', slug: 'togo', isDeveloping: true, countryCode: 'tg', continent: 'africa' },
  { id: 'TN', name: 'チュニジア', slug: 'tunisia', isDeveloping: true, countryCode: 'tn', continent: 'africa' },
  { id: 'UG', name: 'ウガンダ', slug: 'uganda', isDeveloping: true, countryCode: 'ug', continent: 'africa' },
  { id: 'ZM', name: 'ザンビア', slug: 'zambia', isDeveloping: true, countryCode: 'zm', continent: 'africa' },
  { id: 'ZW', name: 'ジンバブエ', slug: 'zimbabwe', isDeveloping: true, countryCode: 'zw', continent: 'africa' },

  // ヨーロッパ
  { id: 'AL', name: 'アルバニア', slug: 'albania', isDeveloping: true, countryCode: 'al', continent: 'europe' },
  { id: 'AD', name: 'アンドラ', slug: 'andorra', isDeveloping: false, countryCode: 'ad', continent: 'europe' },
  { id: 'AT', name: 'オーストリア', slug: 'austria', isDeveloping: false, countryCode: 'at', continent: 'europe' },
  { id: 'BY', name: 'ベラルーシ', slug: 'belarus', isDeveloping: true, countryCode: 'by', continent: 'europe' },
  { id: 'BE', name: 'ベルギー', slug: 'belgium', isDeveloping: false, countryCode: 'be', continent: 'europe' },
  {
    id: 'BA',
    name: 'ボスニア・ヘルツェゴビナ',
    slug: 'bosnia-and-herzegovina',
    isDeveloping: true,
    countryCode: 'ba',
    continent: 'europe',
  },
  { id: 'BG', name: 'ブルガリア', slug: 'bulgaria', isDeveloping: true, countryCode: 'bg', continent: 'europe' },
  { id: 'HR', name: 'クロアチア', slug: 'croatia', isDeveloping: false, countryCode: 'hr', continent: 'europe' },
  { id: 'CZ', name: 'チェコ', slug: 'czech-republic', isDeveloping: false, countryCode: 'cz', continent: 'europe' },
  { id: 'DK', name: 'デンマーク', slug: 'denmark', isDeveloping: false, countryCode: 'dk', continent: 'europe' },
  { id: 'EE', name: 'エストニア', slug: 'estonia', isDeveloping: false, countryCode: 'ee', continent: 'europe' },
  { id: 'FI', name: 'フィンランド', slug: 'finland', isDeveloping: false, countryCode: 'fi', continent: 'europe' },
  { id: 'FR', name: 'フランス', slug: 'france', isDeveloping: false, countryCode: 'fr', continent: 'europe' },
  { id: 'DE', name: 'ドイツ', slug: 'germany', isDeveloping: false, countryCode: 'de', continent: 'europe' },
  { id: 'GR', name: 'ギリシャ', slug: 'greece', isDeveloping: false, countryCode: 'gr', continent: 'europe' },
  { id: 'HU', name: 'ハンガリー', slug: 'hungary', isDeveloping: false, countryCode: 'hu', continent: 'europe' },
  { id: 'IS', name: 'アイスランド', slug: 'iceland', isDeveloping: false, countryCode: 'is', continent: 'europe' },
  { id: 'IE', name: 'アイルランド', slug: 'ireland', isDeveloping: false, countryCode: 'ie', continent: 'europe' },
  { id: 'IT', name: 'イタリア', slug: 'italy', isDeveloping: false, countryCode: 'it', continent: 'europe' },
  { id: 'XK', name: 'コソボ', slug: 'kosovo', isDeveloping: true, countryCode: 'xk', continent: 'europe' },
  { id: 'LV', name: 'ラトビア', slug: 'latvia', isDeveloping: false, countryCode: 'lv', continent: 'europe' },
  {
    id: 'LI',
    name: 'リヒテンシュタイン',
    slug: 'liechtenstein',
    isDeveloping: false,
    countryCode: 'li',
    continent: 'europe',
  },
  { id: 'LT', name: 'リトアニア', slug: 'lithuania', isDeveloping: false, countryCode: 'lt', continent: 'europe' },
  { id: 'LU', name: 'ルクセンブルク', slug: 'luxembourg', isDeveloping: false, countryCode: 'lu', continent: 'europe' },
  { id: 'MT', name: 'マルタ', slug: 'malta', isDeveloping: false, countryCode: 'mt', continent: 'europe' },
  { id: 'MD', name: 'モルドバ', slug: 'moldova', isDeveloping: true, countryCode: 'md', continent: 'europe' },
  { id: 'MC', name: 'モナコ', slug: 'monaco', isDeveloping: false, countryCode: 'mc', continent: 'europe' },
  { id: 'ME', name: 'モンテネグロ', slug: 'montenegro', isDeveloping: true, countryCode: 'me', continent: 'europe' },
  { id: 'NL', name: 'オランダ', slug: 'netherlands', isDeveloping: false, countryCode: 'nl', continent: 'europe' },
  {
    id: 'MK',
    name: '北マケドニア',
    slug: 'north-macedonia',
    isDeveloping: true,
    countryCode: 'mk',
    continent: 'europe',
  },
  { id: 'NO', name: 'ノルウェー', slug: 'norway', isDeveloping: false, countryCode: 'no', continent: 'europe' },
  { id: 'PL', name: 'ポーランド', slug: 'poland', isDeveloping: false, countryCode: 'pl', continent: 'europe' },
  { id: 'PT', name: 'ポルトガル', slug: 'portugal', isDeveloping: false, countryCode: 'pt', continent: 'europe' },
  { id: 'RO', name: 'ルーマニア', slug: 'romania', isDeveloping: true, countryCode: 'ro', continent: 'europe' },
  { id: 'RU', name: 'ロシア', slug: 'russia', isDeveloping: true, countryCode: 'ru', continent: 'europe' },
  { id: 'SM', name: 'サンマリノ', slug: 'san-marino', isDeveloping: false, countryCode: 'sm', continent: 'europe' },
  { id: 'RS', name: 'セルビア', slug: 'serbia', isDeveloping: true, countryCode: 'rs', continent: 'europe' },
  { id: 'SK', name: 'スロバキア', slug: 'slovakia', isDeveloping: false, countryCode: 'sk', continent: 'europe' },
  { id: 'SI', name: 'スロベニア', slug: 'slovenia', isDeveloping: false, countryCode: 'si', continent: 'europe' },
  { id: 'ES', name: 'スペイン', slug: 'spain', isDeveloping: false, countryCode: 'es', continent: 'europe' },
  { id: 'SE', name: 'スウェーデン', slug: 'sweden', isDeveloping: false, countryCode: 'se', continent: 'europe' },
  { id: 'CH', name: 'スイス', slug: 'switzerland', isDeveloping: false, countryCode: 'ch', continent: 'europe' },
  { id: 'UA', name: 'ウクライナ', slug: 'ukraine', isDeveloping: true, countryCode: 'ua', continent: 'europe' },
  { id: 'GB', name: 'イギリス', slug: 'united-kingdom', isDeveloping: false, countryCode: 'gb', continent: 'europe' },
  { id: 'VA', name: 'バチカン市国', slug: 'vatican-city', isDeveloping: false, countryCode: 'va', continent: 'europe' },

  // 北米
  {
    id: 'AG',
    name: 'アンティグア・バーブーダ',
    slug: 'antigua-and-barbuda',
    isDeveloping: true,
    countryCode: 'ag',
    continent: 'north_america',
  },
  { id: 'BS', name: 'バハマ', slug: 'bahamas', isDeveloping: true, countryCode: 'bs', continent: 'north_america' },
  { id: 'BB', name: 'バルバドス', slug: 'barbados', isDeveloping: true, countryCode: 'bb', continent: 'north_america' },
  { id: 'BZ', name: 'ベリーズ', slug: 'belize', isDeveloping: true, countryCode: 'bz', continent: 'north_america' },
  { id: 'CA', name: 'カナダ', slug: 'canada', isDeveloping: false, countryCode: 'ca', continent: 'north_america' },
  {
    id: 'CR',
    name: 'コスタリカ',
    slug: 'costa-rica',
    isDeveloping: true,
    countryCode: 'cr',
    continent: 'north_america',
  },
  { id: 'CU', name: 'キューバ', slug: 'cuba', isDeveloping: true, countryCode: 'cu', continent: 'north_america' },
  { id: 'DM', name: 'ドミニカ国', slug: 'dominica', isDeveloping: true, countryCode: 'dm', continent: 'north_america' },
  {
    id: 'DO',
    name: 'ドミニカ共和国',
    slug: 'dominican-republic',
    isDeveloping: true,
    countryCode: 'do',
    continent: 'north_america',
  },
  {
    id: 'SV',
    name: 'エルサルバドル',
    slug: 'el-salvador',
    isDeveloping: true,
    countryCode: 'sv',
    continent: 'north_america',
  },
  { id: 'GD', name: 'グレナダ', slug: 'grenada', isDeveloping: true, countryCode: 'gd', continent: 'north_america' },
  {
    id: 'GT',
    name: 'グアテマラ',
    slug: 'guatemala',
    isDeveloping: true,
    countryCode: 'gt',
    continent: 'north_america',
  },
  { id: 'HT', name: 'ハイチ', slug: 'haiti', isDeveloping: true, countryCode: 'ht', continent: 'north_america' },
  {
    id: 'HN',
    name: 'ホンジュラス',
    slug: 'honduras',
    isDeveloping: true,
    countryCode: 'hn',
    continent: 'north_america',
  },
  { id: 'JM', name: 'ジャマイカ', slug: 'jamaica', isDeveloping: true, countryCode: 'jm', continent: 'north_america' },
  { id: 'MX', name: 'メキシコ', slug: 'mexico', isDeveloping: true, countryCode: 'mx', continent: 'north_america' },
  {
    id: 'NI',
    name: 'ニカラグア',
    slug: 'nicaragua',
    isDeveloping: true,
    countryCode: 'ni',
    continent: 'north_america',
  },
  { id: 'PA', name: 'パナマ', slug: 'panama', isDeveloping: true, countryCode: 'pa', continent: 'north_america' },
  {
    id: 'KN',
    name: 'セントクリストファー・ネイビス',
    slug: 'saint-kitts-and-nevis',
    isDeveloping: true,
    countryCode: 'kn',
    continent: 'north_america',
  },
  {
    id: 'LC',
    name: 'セントルシア',
    slug: 'saint-lucia',
    isDeveloping: true,
    countryCode: 'lc',
    continent: 'north_america',
  },
  {
    id: 'VC',
    name: 'セントビンセント・グレナディーン',
    slug: 'saint-vincent-and-the-grenadines',
    isDeveloping: true,
    countryCode: 'vc',
    continent: 'north_america',
  },
  {
    id: 'TT',
    name: 'トリニダード・トバゴ',
    slug: 'trinidad-and-tobago',
    isDeveloping: true,
    countryCode: 'tt',
    continent: 'north_america',
  },
  {
    id: 'US',
    name: 'アメリカ合衆国',
    slug: 'united-states',
    isDeveloping: false,
    countryCode: 'us',
    continent: 'north_america',
  },

  // 南米
  {
    id: 'AR',
    name: 'アルゼンチン',
    slug: 'argentina',
    isDeveloping: true,
    countryCode: 'ar',
    continent: 'south_america',
  },
  { id: 'BO', name: 'ボリビア', slug: 'bolivia', isDeveloping: true, countryCode: 'bo', continent: 'south_america' },
  { id: 'BR', name: 'ブラジル', slug: 'brazil', isDeveloping: true, countryCode: 'br', continent: 'south_america' },
  { id: 'CL', name: 'チリ', slug: 'chile', isDeveloping: true, countryCode: 'cl', continent: 'south_america' },
  { id: 'CO', name: 'コロンビア', slug: 'colombia', isDeveloping: true, countryCode: 'co', continent: 'south_america' },
  { id: 'EC', name: 'エクアドル', slug: 'ecuador', isDeveloping: true, countryCode: 'ec', continent: 'south_america' },
  { id: 'GY', name: 'ガイアナ', slug: 'guyana', isDeveloping: true, countryCode: 'gy', continent: 'south_america' },
  { id: 'PY', name: 'パラグアイ', slug: 'paraguay', isDeveloping: true, countryCode: 'py', continent: 'south_america' },
  { id: 'PE', name: 'ペルー', slug: 'peru', isDeveloping: true, countryCode: 'pe', continent: 'south_america' },
  { id: 'SR', name: 'スリナム', slug: 'suriname', isDeveloping: true, countryCode: 'sr', continent: 'south_america' },
  { id: 'UY', name: 'ウルグアイ', slug: 'uruguay', isDeveloping: true, countryCode: 'uy', continent: 'south_america' },
  {
    id: 'VE',
    name: 'ベネズエラ',
    slug: 'venezuela',
    isDeveloping: true,
    countryCode: 've',
    continent: 'south_america',
  },

  // オセアニア
  { id: 'AU', name: 'オーストラリア', slug: 'australia', isDeveloping: false, countryCode: 'au', continent: 'oceania' },
  { id: 'FJ', name: 'フィジー', slug: 'fiji', isDeveloping: true, countryCode: 'fj', continent: 'oceania' },
  { id: 'KI', name: 'キリバス', slug: 'kiribati', isDeveloping: true, countryCode: 'ki', continent: 'oceania' },
  {
    id: 'MH',
    name: 'マーシャル諸島',
    slug: 'marshall-islands',
    isDeveloping: true,
    countryCode: 'mh',
    continent: 'oceania',
  },
  {
    id: 'FM',
    name: 'ミクロネシア連邦',
    slug: 'micronesia',
    isDeveloping: true,
    countryCode: 'fm',
    continent: 'oceania',
  },
  { id: 'NR', name: 'ナウル', slug: 'nauru', isDeveloping: true, countryCode: 'nr', continent: 'oceania' },
  {
    id: 'NZ',
    name: 'ニュージーランド',
    slug: 'new-zealand',
    isDeveloping: false,
    countryCode: 'nz',
    continent: 'oceania',
  },
  { id: 'PW', name: 'パラオ', slug: 'palau', isDeveloping: true, countryCode: 'pw', continent: 'oceania' },
  {
    id: 'PG',
    name: 'パプアニューギニア',
    slug: 'papua-new-guinea',
    isDeveloping: true,
    countryCode: 'pg',
    continent: 'oceania',
  },
  { id: 'WS', name: 'サモア', slug: 'samoa', isDeveloping: true, countryCode: 'ws', continent: 'oceania' },
  {
    id: 'SB',
    name: 'ソロモン諸島',
    slug: 'solomon-islands',
    isDeveloping: true,
    countryCode: 'sb',
    continent: 'oceania',
  },
  { id: 'TO', name: 'トンガ', slug: 'tonga', isDeveloping: true, countryCode: 'to', continent: 'oceania' },
  { id: 'TV', name: 'ツバル', slug: 'tuvalu', isDeveloping: true, countryCode: 'tv', continent: 'oceania' },
  { id: 'VU', name: 'バヌアツ', slug: 'vanuatu', isDeveloping: true, countryCode: 'vu', continent: 'oceania' },
];
