export const users = [
  {
    id: 1,
    name: '山田 花子',
    countryId: 26,
    prefecture: '愛知県',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
  {
    id: 2,
    name: '田中 一郎',
    countryId: 1,
    prefecture: '東京都',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
  {
    id: 3,
    name: '鈴木 次郎',
    countryId: 54,
    prefecture: '大阪府',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
  {
    id: 4,
    name: '伊藤 三郎',
    countryId: 39,
    prefecture: '福岡県',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
  {
    id: 5,
    name: '佐藤 四郎',
    countryId: 26,
    prefecture: '北海道',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
  {
    id: 6,
    name: '高橋 五郎',
    countryId: 21,
    prefecture: '沖縄県',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
  {
    id: 7,
    name: '小林 六郎',
    countryId: 61,
    prefecture: '宮城県',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
  {
    id: 8,
    name: '加藤 七郎',
    countryId: 151,
    prefecture: '静岡県',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
  {
    id: 9,
    name: '吉田 八郎',
    countryId: 131,
    prefecture: '広島県',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
  {
    id: 10,
    name: '中村 九郎',
    countryId: 85,
    prefecture: '京都府',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
  {
    id: 11,
    name: '小野 十郎',
    countryId: 6,
    prefecture: '奈良県',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
  {
    id: 12,
    name: '伊東 十一郎',
    countryId: 142,
    prefecture: '岐阜県',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
  {
    id: 13,
    name: '山本 十二郎',
    countryId: 122,
    prefecture: '山口県',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
  {
    id: 14,
    name: '中島 十三郎',
    countryId: 145,
    prefecture: '神奈川県',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
  {
    id: 15,
    name: '村上 十四郎',
    countryId: 49,
    prefecture: '群馬県',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
  {
    id: 16,
    name: '江口 十五郎',
    countryId: 128,
    prefecture: '茨城県',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
  {
    id: 17,
    name: '阿部 十六郎',
    countryId: 26,
    prefecture: '栃木県',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
  {
    id: 18,
    name: '山下 十七郎',
    countryId: 143,
    prefecture: '福井県',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
  {
    id: 19,
    name: '石井 十八郎',
    countryId: 83,
    prefecture: '新潟県',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
  {
    id: 20,
    name: '小川 十九郎',
    countryId: 39,
    prefecture: '滋賀県',
    image: '/images/sample-person.jpg',
    description: 'Hello World',
  },
];
