import type { Metadata } from 'next';
import './globals.css';

import { Inter } from 'next/font/google';
import NextAuthProvider from '@/app/providers/NextAuth';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '協力隊の輪 | 青年海外協力隊のOBOGのプロフィールシェアアプリです',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
