import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import NextAuthProvider from '@/app/providers/NextAuth';
import ToastProvider from '@/components/ToastProvider';
import { SpeedInsights } from '@vercel/speed-insights/next';

export const metadata: Metadata = {
  title: '協力隊の輪 | 青年海外協力隊のOBOGのプロフィールシェアアプリです',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <ToastProvider>
          <NextAuthProvider>{children}</NextAuthProvider>
        </ToastProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
